In [2]:
import pandas as pd

In [3]:
day_rev = pd.read_csv("D:\\SevenMentor\\ML\\workspace\\practes\\Day-Sector-Revenue.csv")

In [4]:
day_rev.head()

   Day         Sector  Revenue
0    1    Agriculture      100
1    1  Manufacturing      200
2    1    IT Services      300
3    2    Agriculture      120
4    2  Manufacturing      180

In [5]:
day_rev.isnull().sum()

Day        0
Sector     0
Revenue    0
dtype: int64

In [6]:
day_rev.Sector.unique()

<StringArray>
['Agriculture', 'Manufacturing', 'IT Services']
Length: 3, dtype: str

In [7]:
day_rev.duplicated().sum()

np.int64(0)

In [8]:
to_rev = day_rev.groupby("Sector")["Revenue"].sum()
to_rev_mean = day_rev.groupby("Sector")["Revenue"].mean()
to_rev_median = day_rev.groupby("Sector")["Revenue"].median()

In [9]:
print(to_rev)
print(to_rev_mean)
print(to_rev_median)

Sector
Agriculture      350
IT Services      970
Manufacturing    590
Name: Revenue, dtype: int64
Sector
Agriculture      116.666667
IT Services      323.333333
Manufacturing    196.666667
Name: Revenue, dtype: float64
Sector
Agriculture      120.0
IT Services      330.0
Manufacturing    200.0
Name: Revenue, dtype: float64

In [13]:
day_rev["Rolling_rev"] = day_rev["Revenue"].rolling(3).mean()

In [14]:
day_rev

   Day         Sector  Revenue  Rolling_rev
0    1    Agriculture      100          NaN
1    1  Manufacturing      200          NaN
2    1    IT Services      300   200.000000
3    2    Agriculture      120   206.666667
4    2  Manufacturing      180   200.000000
5    2    IT Services      330   210.000000
6    3    Agriculture      130   213.333333
7    3  Manufacturing      210   223.333333
8    3    IT Services      340   226.666667