In [1]:
import pandas as pd
import numpy as np

In [2]:
car = pd.read_csv(r"D:\SevenMentor\ML\workspace\Dhanaji_ml\dataset\car_price_regression_data (1).csv")

In [3]:
car

,Brand,Model,Year,Age_Years,Fuel_Type,Transmission,Engine_CC,Kilometers_Driven,Owner_Type,Mileage_kmpl,Seats,Safety_Rating,Price_Lakh
0,Hyundai,Creta,2021,3,Petrol,Automatic,1462,64757,First,21.8,5,2.5,9
1,Honda,City,2015,9,Petrol,Manual,998,182014,First,21.2,7,3.4,2
2,Nissan,Magnite,2017,7,Electric,Manual,0,115619,First,250.5,6,4.8,1
3,Mahindra,Scorpio-N,2016,8,Diesel,Manual,998,117605,First,15.3,5,2.3,4
4,Tata,Altroz,2023,1,Petrol,Manual,998,58118,First,14.4,5,4.6,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Toyota,Innova Crysta,2019,5,Electric,Manual,0,196361,First,324.9,6,3.8,9
96,Nissan,Magnite,2020,4,Petrol,Manual,1497,50908,First,18.8,5,2.9,4
97,Renault,Triber,2021,3,Petrol,Automatic,1956,34332,First,18.2,6,4.8,5
98,Kia,Sonet,2017,7,Petrol,Manual,1497,154893,First,16.1,5,4.8,2
99,Volkswagen,Taigun,2024,0,Diesel,Manual,2184,145932,First,20.1,5,3.9,14

In [4]:
car.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Brand              100 non-null    str
 1   Model              100 non-null    str
 2   Year               100 non-null    int64
 3   Age_Years          100 non-null    int64
 4   Fuel_Type          100 non-null    str
 5   Transmission       100 non-null    str
 6   Engine_CC          100 non-null    int64
 7   Kilometers_Driven  100 non-null    int64
 8   Owner_Type         100 non-null    str
 9   Mileage_kmpl       100 non-null    float64
 10  Seats              100 non-null    int64
 11  Safety_Rating      100 non-null    float64
 12  Price_Lakh         100 non-null    int64
dtypes: float64(2), int64(6), str(5)
memory usage: 10.3 KB

In [5]:
car.isna().sum()

Brand                0
Model                0
Year                 0
Age_Years            0
Fuel_Type            0
Transmission         0
Engine_CC            0
Kilometers_Driven    0
Owner_Type           0
Mileage_kmpl         0
Seats                0
Safety_Rating        0
Price_Lakh           0
dtype: int64

In [6]:
car.duplicated().sum()

np.int64(0)

In [7]:
cat = []
con = []

for i in car.columns:
    if car[i].dtypes == 'str':
        cat.append(i)
    else:
        con.append(i)

In [8]:
cat

['Brand', 'Model', 'Fuel_Type', 'Transmission', 'Owner_Type']

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [10]:
for i in cat:
    car[i] = le.fit_transform(car[i])
    print(le.classes_)

['Honda' 'Hyundai' 'Kia' 'Mahindra' 'Maruti Suzuki' 'Nissan' 'Renault'
 'Skoda' 'Tata' 'Toyota' 'Volkswagen']
['Altroz' 'Amaze' 'Baleno' 'Brezza' 'Carens' 'City' 'Creta' 'Dzire'
 'Fortuner' 'Harrier' 'Innova Crysta' 'Kiger' 'Kushaq' 'Magnite' 'Nexon'
 'Scorpio-N' 'Seltos' 'Slavia' 'Sonet' 'Swift' 'Taigun' 'Thar' 'Triber'
 'Urban Cruiser' 'Venue' 'Verna' 'Virtus' 'Wagon R' 'XUV700' 'i20']
['CNG' 'Diesel' 'Electric' 'Petrol']
['Automatic' 'Manual']
['First' 'Second' 'Third']

In [12]:
car

,Brand,Model,Year,Age_Years,Fuel_Type,Transmission,Engine_CC,Kilometers_Driven,Owner_Type,Mileage_kmpl,Seats,Safety_Rating,Price_Lakh
0,1,6,2021,3,3,0,1462,64757,0,21.8,5,2.5,9
1,0,5,2015,9,3,1,998,182014,0,21.2,7,3.4,2
2,5,13,2017,7,2,1,0,115619,0,250.5,6,4.8,1
3,3,15,2016,8,1,1,998,117605,0,15.3,5,2.3,4
4,8,0,2023,1,3,1,998,58118,0,14.4,5,4.6,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,9,10,2019,5,2,1,0,196361,0,324.9,6,3.8,9
96,5,13,2020,4,3,1,1497,50908,0,18.8,5,2.9,4
97,6,22,2021,3,3,0,1956,34332,0,18.2,6,4.8,5
98,2,18,2017,7,3,1,1497,154893,0,16.1,5,4.8,2
99,10,20,2024,0,1,1,2184,145932,0,20.1,5,3.9,14

In [14]:
X = car.drop('Price_Lakh', axis=1)
y = car['Price_Lakh']

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
lr = LinearRegression()

In [16]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(80, 12) (20, 12) (80,) (20,)

In [19]:
# train model


lr.fit(x_train, y_train)
print(f"Iteration {i}: Train Score: {lr.score(x_train, y_train)}, Test Score: {lr.score(x_test, y_test)}")

Iteration 5: Train Score: 0.425922208766517, Test Score: 0.17435466525501198

based on the output of the above code, it seems that the model is overfitting. The train score is significantly higher than the test score, indicating that the model is performing well on the training data but not generalizing well to unseen data.