In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r"D:\SevenMentor\ML\workspace\Dhanaji_ml\dataset\House Price Prediction Dataset.csv")

In [3]:
data

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056
...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,Suburban,Poor,No,295620
1996,1997,3046,5,2,1,2019,Suburban,Poor,Yes,580929
1997,1998,1062,5,1,2,1903,Rural,Poor,No,476925
1998,1999,4062,3,1,2,1936,Urban,Excellent,Yes,161119
1999,2000,2989,5,1,3,1903,Suburban,Fair,No,482525

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id         2000 non-null   int64
 1   Area       2000 non-null   int64
 2   Bedrooms   2000 non-null   int64
 3   Bathrooms  2000 non-null   int64
 4   Floors     2000 non-null   int64
 5   YearBuilt  2000 non-null   int64
 6   Location   2000 non-null   str
 7   Condition  2000 non-null   str
 8   Garage     2000 non-null   str
 9   Price      2000 non-null   int64
dtypes: int64(7), str(3)
memory usage: 156.4 KB

In [5]:
data.isnull().sum()

Id           0
Area         0
Bedrooms     0
Bathrooms    0
Floors       0
YearBuilt    0
Location     0
Condition    0
Garage       0
Price        0
dtype: int64

In [6]:
X = data.drop(["Price"], axis = 1)
y = data["Price"]

In [7]:
X

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage
0,1,1360,5,4,3,1970,Downtown,Excellent,No
1,2,4272,5,4,3,1958,Downtown,Excellent,No
2,3,3592,2,2,3,1938,Downtown,Good,No
3,4,966,4,2,2,1902,Suburban,Fair,Yes
4,5,4926,1,4,2,1975,Downtown,Fair,Yes
...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,Suburban,Poor,No
1996,1997,3046,5,2,1,2019,Suburban,Poor,Yes
1997,1998,1062,5,1,2,1903,Rural,Poor,No
1998,1999,4062,3,1,2,1936,Urban,Excellent,Yes
1999,2000,2989,5,1,3,1903,Suburban,Fair,No

In [8]:
cat=[]
con=[]


for i in X.columns:
    if X[i].dtype == "str":
        cat.append(i)
    else:
        con.append(i)

In [9]:
categrical_columns = X[cat]
continus_columns = X[con]

In [10]:
categrical_columns

      Location  Condition Garage
0     Downtown  Excellent     No
1     Downtown  Excellent     No
2     Downtown       Good     No
3     Suburban       Fair    Yes
4     Downtown       Fair    Yes
...        ...        ...    ...
1995  Suburban       Poor     No
1996  Suburban       Poor    Yes
1997     Rural       Poor     No
1998     Urban  Excellent    Yes
1999  Suburban       Fair     No

[2000 rows x 3 columns]

In [11]:
continus_columns

        Id  Area  Bedrooms  Bathrooms  Floors  YearBuilt
0        1  1360         5          4       3       1970
1        2  4272         5          4       3       1958
2        3  3592         2          2       3       1938
3        4   966         4          2       2       1902
4        5  4926         1          4       2       1975
...    ...   ...       ...        ...     ...        ...
1995  1996  4994         5          4       3       1923
1996  1997  3046         5          2       1       2019
1997  1998  1062         5          1       2       1903
1998  1999  4062         3          1       2       1936
1999  2000  2989         5          1       3       1903

[2000 rows x 6 columns]

In [12]:
from sklearn.preprocessing import OneHotEncoder

In [13]:
ohe = OneHotEncoder(sparse_output = False)

In [14]:
encode = ohe.fit_transform(categrical_columns)

In [15]:
encode

array([[1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 1., 0.]], shape=(2000, 10))

In [16]:
ohe.get_feature_names_out()

array(['Location_Downtown', 'Location_Rural', 'Location_Suburban',
       'Location_Urban', 'Condition_Excellent', 'Condition_Fair',
       'Condition_Good', 'Condition_Poor', 'Garage_No', 'Garage_Yes'],
      dtype=object)

In [17]:
a = pd.DataFrame(encode, columns = ohe.get_feature_names_out().tolist())

In [18]:
new_df = pd.concat([continus_columns, a], axis = 1)

In [19]:
new_df

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location_Downtown,Location_Rural,Location_Suburban,Location_Urban,Condition_Excellent,Condition_Fair,Condition_Good,Condition_Poor,Garage_No,Garage_Yes
0,1,1360,5,4,3,1970,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,2,4272,5,4,3,1958,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,3,3592,2,2,3,1938,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,4,966,4,2,2,1902,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,5,4926,1,4,2,1975,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1996,1997,3046,5,2,1,2019,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1997,1998,1062,5,1,2,1903,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1998,1999,4062,3,1,2,1936,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
1999,2000,2989,5,1,3,1903,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
xtrain, xtest, ytrain, ytest = train_test_split(new_df, y, test_size = 0.2, random_state = 42, shuffle = True)

In [22]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

model=lr.fit(xtrain,ytrain)

In [23]:
pred_tr=model.predict(xtrain)
pred_ts=model.predict(xtest)

In [24]:
pred_tr

array([523593.72106321, 500483.32076083, 475823.8729011 , ...,
       540296.25230004, 475424.86926272, 571641.52902076], shape=(1600,))

In [25]:
pred_ts

array([511317.73109931, 557359.55652936, 482838.34523391, 540695.6411198 ,
       549288.50244107, 518144.16928401, 523405.40235976, 568346.51627797,
       556990.3977267 , 573402.71846042, 560327.02526869, 580125.07750594,
       509628.89913772, 532492.70848044, 509721.56444397, 572094.84475122,
       536987.54980342, 567213.27046174, 571135.70064566, 512073.55283631,
       539312.23348974, 511844.49461755, 508598.43117479, 589678.62607714,
       559483.71580206, 540987.05449051, 522708.73013649, 534204.67811389,
       520198.55289369, 500920.60216369, 475555.72605338, 533069.83976321,
       564818.74920608, 567197.08659151, 504221.60797606, 510451.11954577,
       559173.27166252, 583163.79071258, 532087.00828381, 512605.87316523,
       499271.26212725, 530223.34803808, 547450.7379217 , 543281.28975282,
       533429.88712312, 575342.14120786, 557923.59595814, 538457.64588905,
       542099.1954386 , 521037.26607699, 508733.44694034, 558684.27065773,
       561335.50693823, 554953.43407551, 518495.85848992, 532306.71684625,
       569070.26287433, 494674.25261683, 503868.63947747, 522859.62295564,
       541252.78918408, 502315.58392067, 535453.62117749, 540338.26567059,
       545221.2525514 , 478333.70792501, 501361.61749707, 538212.17469263,
       547288.52530794, 557724.71108623, 564108.72750708, 581563.44326233,
       554954.00838597, 561924.97187872, 533160.76145665, 589605.64998588,
       559304.95526747, 562976.07416583, 561186.11952223, 505985.93331516,
       522298.27603687, 583986.58310953, 523126.79949241, 506055.83142789,
       556809.23605798, 481382.92550552, 518432.14120321, 561858.50576044,
       528928.12653567, 523117.36505049, 532853.85858869, 536075.28837267,
       594907.60575162, 590783.54493948, 561844.79194917, 497463.09613791,
       565028.34317316, 511214.72983614, 506725.64386907, 509771.40022646,
       552990.29528634, 521913.42548822, 565119.1044497 , 504910.48981767,
       471931.9277232 , 535068.08318237, 510861.41922456, 563409.00195439,
       564882.70602425, 500387.96621475, 556570.3549525 , 511944.44731787,
       494183.36834367, 567663.27932251, 563413.42493137, 536701.38412295,
       482541.77831583, 555252.40277922, 590259.55853636, 578080.47771481,
       544963.12410229, 523251.21644284, 562261.81786706, 548405.04735818,
       538507.82383558, 550592.93669286, 524206.80548524, 508413.4333149 ,
       512217.93415289, 571648.64269237, 546216.33585802, 573741.1666502 ,
       538512.40383483, 497764.77742154, 549276.70719248, 537675.62889476,
       548163.2680041 , 522824.52625148, 564236.38210155, 572755.46987951,
       530905.07813308, 504554.21349456, 534419.81929279, 545779.14416282,
       540738.23807079, 558897.53539983, 558130.26193948, 483332.20686888,
       595950.48610278, 550936.77909606, 518305.54432337, 528052.39234616,
       552730.25525851, 483219.09435107, 558876.92813812, 537562.41463015,
       540641.2871259 , 564457.95833234, 524376.54640408, 523951.69124289,
       543391.46821948, 544338.3812417 , 557718.15212699, 533276.83789203,
       545620.34608608, 547616.96628383, 553372.94850003, 540784.34651279,
       484977.66677059, 529750.1799711 , 473265.06823416, 533879.60723206,
       523180.74316868, 498204.15476924, 522519.04241582, 510124.06896164,
       582914.69569821, 536584.70816641, 572303.89742723, 545016.84493781,
       529686.86598385, 526718.2220863 , 520794.68729654, 522844.21964371,
       507917.13742163, 527994.89017689, 517006.74681865, 518144.71268749,
       536336.95408793, 527009.67532976, 557588.43370946, 505546.88860094,
       522647.75384452, 556617.89952403, 550551.83834675, 533884.22321332,
       525711.70254754, 533610.27063503, 546395.68394633, 538018.10550262,
       508933.57318084, 486766.46392119, 541516.58743221, 570579.91817008,
       527254.127251  , 532955.97360032, 474453.79265548, 525340.91348447,
       551353.75378111, 581617.60798353, 527278.96394446, 549034.90879822,
       504790.46483954, 536673.21420397, 504737.7608565 , 473972.54901458,
       493104.55596271, 574621.60438476, 557110.37241497, 509425.08992009,
       536158.41297402, 564104.31453015, 509885.53715874, 522052.49895493,
       530994.58921839, 473099.40594981, 553156.25844455, 532448.24151681,
       519586.80457142, 568126.90778764, 510072.73283542, 542786.74759247,
       552872.60500577, 555799.90352359, 535700.56150593, 562903.5846506 ,
       553434.21722256, 580428.18944213, 511138.5384076 , 523570.34722171,
       566985.48643535, 542279.99658612, 551141.50654687, 531429.56877058,
       517911.37444467, 547773.2632589 , 586022.64504152, 519470.81092086,
       542285.02685342, 480775.78069319, 561480.40964653, 555578.07510669,
       543369.58977046, 518631.46680764, 522060.65016526, 479839.55485628,
       599323.41430951, 511123.57478843, 482179.39544134, 492457.94124403,
       550398.17561173, 480058.0923996 , 546037.58866469, 529168.11520608,
       538661.21519348, 518582.2223299 , 540065.20580187, 528645.02502227,
       519219.80874144, 490337.75814133, 516748.57559352, 545671.83285533,
       579126.68213967, 540943.93646162, 527564.06160605, 557967.21043367,
       553381.78640257, 525090.83034453, 538543.08181593, 520134.46675621,
       498124.01060041, 558448.63728364, 548523.82459997, 542404.38389148,
       547436.24699286, 523976.97209326, 491833.081089  , 493164.47120123,
       571907.38356874, 511876.39428467, 506622.24120197, 482566.04680773,
       526050.17790385, 525320.91686893, 537339.70698564, 554265.7151377 ,
       516509.15662298, 548595.35097584, 560740.09124411, 514402.49294577,
       525486.13437749, 573589.97262107, 488303.48743285, 533019.55834054,
       480818.81705548, 549166.37629579, 502546.27902709, 582002.61307483,
       505844.02766242, 541929.74854218, 506427.29494644, 551967.88691128,
       539295.61781103, 525029.48962258, 545769.76991938, 564795.95238206,
       553938.14986499, 534118.38871147, 530792.67220463, 497195.56932711,
       533799.72387585, 517474.51772933, 575043.50003439, 523412.2630418 ,
       513299.40784502, 582322.56614366, 529998.61246431, 548383.97768491,
       571731.93715809, 484990.16890256, 532671.1853677 , 522716.4973158 ,
       499161.79691794, 543458.1718495 , 557808.32479757, 504486.25742145,
       522041.18898726, 555013.94517937, 549121.85019562, 552010.62601795,
       499448.1788552 , 555437.09799799, 500648.09124565, 563328.92009851,
       544960.57812999, 544599.61491572, 539128.73814563, 515242.09094013,
       552768.8496668 , 485598.77357844, 519997.20190181, 547128.90215331,
       542976.55950067, 494506.49474137, 539800.51695427, 553919.42158786,
       535642.61192332, 552884.85382966, 525759.57486022, 520075.11254858,
       526386.8294861 , 564335.7594927 , 492312.72711532, 497844.24259701,
       551520.50955078, 548513.04382049, 488417.81918593, 539048.42117924,
       491069.37656168, 516976.91262969, 535499.01424041, 523693.78274144,
       605191.98404184, 575422.25636062, 534300.01414645, 534142.21378907,
       513765.1244927 , 591857.73287785, 534917.52880182, 507454.35888354,
       511924.62785265, 587404.13866669, 594484.8326283 , 528631.02806022,
       553059.47414542, 546454.69157875, 537706.40704416, 535139.38982047,
       502360.42464145, 524904.68156433, 512668.80315401, 533212.98944719,
       524702.49270749, 531571.67080196, 541353.10755439, 557737.98807809,
       546173.34311987, 511120.81806491, 527705.13238654, 548574.43021391])

In [26]:
y_obse = pd.DataFrame(ytest)

In [27]:
y_obse["Price_pred"] = pred_ts

In [31]:
y_obse.head(50)

       Price     Price_pred
1860  514764  511317.731099
353   694256  557359.556529
1333   66375  482838.345234
905   650243  540695.641120
1289  223285  549288.502441
1273  468127  518144.169284
938   513002  523405.402360
1731  911525  568346.516278
65    723265  556990.397727
1323  339416  573402.718460
56    913498  560327.025269
1292  657493  580125.077506
1118  259727  509628.899138
584   345187  532492.708480
374   688751  509721.564444
275   777513  572094.844751
746   506388  536987.549803
128   589618  567213.270462
1646  984581  571135.700646
1852  683801  512073.552836
674   697861  539312.233490
1664  464248  511844.494618
1981  663529  508598.431175
1083  578742  589678.626077
1922  673944  559483.715802
99    777688  540987.054491
1179  402131  522708.730136
964   628528  534204.678114
792   759441  520198.552894
29    206547  500920.602164
628   908754  475555.726053
944   821668  533069.839763
572   292726  564818.749206
907   144791  567197.086592
1080  788661  504221.607976
450   857605  510451.119546
1609  490691  559173.271663
1290  681866  583163.790713
1078  545951  532087.008284
254   317724  512605.873165
124   180509  499271.262127
1927  193092  530223.348038
251   866037  547450.737922
585   186343  543281.289753
1568  270172  533429.887123
824   760595  575342.141208
507   684157  557923.595958
889   367006  538457.645889
70    689604  542099.195439
1608  174451  521037.266077

# Model Evaluation

In [29]:
from sklearn.metrics import accuracy_score as acc
tr_err = acc(ytrain, pred_tr)
ts_err = acc(ytest,pred_ts)

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

In [ ]:
from sklearn.metrics import mean_absolute_error
tr_err=mean_absolute_error(ytrain, pred_tr)
ts_err=mean_absolute_error(ytest, pred_ts)

In [ ]:
tr_err

In [ ]:
ts_err