In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
market = pd.read_csv("D:\\SevenMentor\\ML\\workspace\\Dataset\\Stock Market data .csv")

In [3]:
market

,Share,Category,Sector,RM,Up,Last Traded Price,Percentage Change,High Price,Low Price,% High Movt,...,Annual_Eps,Volume,MarketCap,Annual_Pat.1,EquityCapital,FaceValue,New Listing,PE High Price High,Future,Cap Category
0,20MICRONS,Exit,CHEMICALS,NaN,NaN,43.00,NaN,NaN,NaN,NaN,...,3.11,0.532215,152,11.0609,17.6433,5,NaN,NaN,NaN,MiniCap
1,3IINFOTECH,BWLV,IT,NaN,NaN,5.35,NaN,NaN,NaN,NaN,...,-16.96,1.164510,633,-1059.27,1047.45,10,NaN,NaN,NaN,MiniCap
2,3MINDIA,Exit,DIVERSIFIED,0,0,12219.65,1.23,12399.95,12115.0,0.014540381,...,178.36,1.041870,13766,200.9298,11.2651,10,NaN,NaN,NaN,MidCap
3,63MOONS,RS,IT,NaN,NaN,75.60,0.26,76.70,75.6,0.014341591,...,0,1.250000,348,0,9.2157,2,NaN,NaN,NaN,MiniCap
4,8KMILES,HWV,IT,0,0,623.90,0.17,640.00,624.0,0.02515625,...,36.34,4.816666,1904,53.2361,15.2588,5,NaN,NaN,NaN,SmallCap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1564,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
market.info()

<class 'pandas.DataFrame'>
RangeIndex: 1568 entries, 0 to 1567
Data columns (total 63 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Share                     1562 non-null   str
 1   Category                  1544 non-null   str
 2   Sector                    1560 non-null   str
 3   RM                        578 non-null    str
 4   Up                        583 non-null    str
 5   Last Traded Price         1548 non-null   float64
 6   Percentage Change         969 non-null    float64
 7   High Price                969 non-null    float64
 8   Low Price                 969 non-null    float64
 9   % High Movt               958 non-null    str
 10  % Low movt                958 non-null    str
 11  Yearly Gainner            1388 non-null   str
 12  27th Dec                  1457 non-null   str
 13  1st Feb                   1487 non-null   str
 14  1st March                 1500 non-null   str
 15  1st April                 1509 non-null   str
 16  TB                        435 non-null    str
 17  RH                        1527 non-null   float64
 18  Corr                      1508 non-null   str
 19  PeRatio                   1554 non-null   float64
 20  New Pe                    1532 non-null   str
 21  W52_High                  1560 non-null   float64
 22  Corre                     1532 non-null   str
 23  latest                    661 non-null    float64
 24  Annual_Pat                1524 non-null   float64
 25  Cum PAT 3 Quarter         1515 non-null   float64
 26  Pat Jump                  1501 non-null   float64
 27  Annual Growth             563 non-null    str
 28  Year End                  15 non-null     str
 29  Mar_17_ReportedPAT        953 non-null    float64
 30  Dec_16_ReportedPAT        1547 non-null   float64
 31  Sep_16_ReportedPAT        1538 non-null   float64
 32  Jun_16_ReportedPAT        1532 non-null   float64
 33  Mar_16_ReportedPAT        1526 non-null   float64
 34  Dec_15_ReportedPAT        1525 non-null   float64
 35  Y oY PAT                  993 non-null    str
 36  LQ>0.5(4q's)              42 non-null     str
 37  PAT Growth                1035 non-null   str
 38  PeRatio.1                 1554 non-null   float64
 39  ResultDate                1551 non-null   float64
 40  Mar_17_Inst_no_of_shares  1503 non-null   float64
 41  Dec_16_Inst_no_of_shares  1494 non-null   float64
 42  Int/ Incr/ Decr           1400 non-null   float64
 43  Pledge                    1554 non-null   float64
 44  DividendYield             1554 non-null   float64
 45  DERatio                   1554 non-null   float64
 46  FB                        691 non-null    str
 47  Mar_17_Eps_Before         1560 non-null   str
 48  Dec_16_Eps_Before         1560 non-null   str
 49  Sep_16_Eps_Before         1560 non-null   str
 50  Jun_16_Eps_Before         1560 non-null   str
 51  Mar_16_Eps_Before         1560 non-null   str
 52  Dec_15_Eps_Before         1560 non-null   str
 53  Annual_Eps                1560 non-null   str
 54  Volume                    1545 non-null   float64
 55  MarketCap                 1560 non-null   str
 56  Annual_Pat.1              1560 non-null   str
 57  EquityCapital             1560 non-null   str
 58  FaceValue                 1560 non-null   str
 59  New Listing               91 non-null     str
 60  PE High Price High        0 non-null      float64
 61  Future                    46 non-null     str
 62  Cap Category              1545 non-null   str
dtypes: float64(27), str(36)
memory usage: 771.9 KB

In [25]:
market.isnull().sum()

Share                    6
Category                24
Sector                   8
RM                     990
Up                     985
                      ...
FaceValue                8
New Listing           1477
PE High Price High    1568
Future                1522
Cap Category            23
Length: 63, dtype: int64

In [26]:
market.duplicated().sum()

np.int64(1)

In [27]:
market

,Share,Category,Sector,RM,Up,Last Traded Price,Percentage Change,High Price,Low Price,% High Movt,...,Annual_Eps,Volume,MarketCap,Annual_Pat.1,EquityCapital,FaceValue,New Listing,PE High Price High,Future,Cap Category
0,20MICRONS,Exit,CHEMICALS,NaN,NaN,43.00,NaN,NaN,NaN,NaN,...,3.11,0.532215,152,11.0609,17.6433,5,NaN,NaN,NaN,MiniCap
1,3IINFOTECH,BWLV,IT,NaN,NaN,5.35,NaN,NaN,NaN,NaN,...,-16.96,1.164510,633,-1059.27,1047.45,10,NaN,NaN,NaN,MiniCap
2,3MINDIA,Exit,DIVERSIFIED,0,0,12219.65,1.23,12399.95,12115.0,0.014540381,...,178.36,1.041870,13766,200.9298,11.2651,10,NaN,NaN,NaN,MidCap
3,63MOONS,RS,IT,NaN,NaN,75.60,0.26,76.70,75.6,0.014341591,...,0,1.250000,348,0,9.2157,2,NaN,NaN,NaN,MiniCap
4,8KMILES,HWV,IT,0,0,623.90,0.17,640.00,624.0,0.02515625,...,36.34,4.816666,1904,53.2361,15.2588,5,NaN,NaN,NaN,SmallCap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1564,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
new_market = market.drop_duplicates()

In [23]:
new_market = new_market.dropna(
    subset=["TB", "Year End", "LQ>0.5(4q's)", "PE High Price High", "Cap Category", "New Listing"]
)

In [24]:
new_market

Empty DataFrame
Columns: [Share, Category, Sector, RM, Up, Last Traded Price, Percentage Change, High Price, Low Price, % High Movt, % Low movt, Yearly Gainner, 27th Dec, 1st Feb, 1st March, 1st April, TB, RH, Corr, PeRatio, New Pe, W52_High, Corre, latest, Annual_Pat, Cum PAT 3 Quarter, Pat Jump, Annual Growth, Year End, Mar_17_ReportedPAT, Dec_16_ReportedPAT, Sep_16_ReportedPAT, Jun_16_ReportedPAT, Mar_16_ReportedPAT, Dec_15_ReportedPAT, Y oY PAT, LQ>0.5(4q's), PAT Growth, PeRatio.1, ResultDate, Mar_17_Inst_no_of_shares, Dec_16_Inst_no_of_shares, Int/ Incr/ Decr, Pledge, DividendYield, DERatio, FB, Mar_17_Eps_Before, Dec_16_Eps_Before, Sep_16_Eps_Before, Jun_16_Eps_Before, Mar_16_Eps_Before, Dec_15_Eps_Before, Annual_Eps, Volume, MarketCap, Annual_Pat.1, EquityCapital, FaceValue, New Listing, PE High Price High, Future, Cap Category]
Index: []

[0 rows x 63 columns]